#!/bin/bash

LOGFILE=~/testbench/.server/server_log.txt

sudo killall testbench_server > /dev/null 2>&1

echo "" >> ${LOGFILE}
echo "" >> ${LOGFILE}
echo "" >> ${LOGFILE}
echo "########################### SESSION STARTED ##############################" >> ${LOGFILE}
sudo nohup ~/testbench/.server/testbench_server >> ${LOGFILE} 2>&1 &
