#!/bin/bash

LOGFILE=/home/pi/testbench/.server/server_log.txt
SERVERBIN=/home/pi/testbench/.server/testbench_server

sudo killall testbench_server > /dev/null 2>&1

echo "" >> ${LOGFILE}
echo "" >> ${LOGFILE}
echo "" >> ${LOGFILE}
echo "########################### SESSION STARTED ##############################" >> ${LOGFILE}
sudo nohup ${SERVERBIN} >> ${LOGFILE} 2>&1 &
