#!/usr/bin/python3
import socket
import sys
import time


HOST = '127.0.0.1'
PORT = 12345

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((HOST, PORT))

#                       MAGIC                       type    size        type    argc    args[...]
command_rfid = bytes([  0x41, 0x42, 0x13, 0x56,     0,      0, 2,       0x99,   0])

n = client.send(command_rfid)
if (n != len(command_rfid)):
    print ('Erreur envoi.')

time.sleep(1)
client.close()
