#!/usr/bin/python3
import socket
import sys
import time

if len(sys.argv) != 2:
    print('vous pouvez repeter la question?')
    exit()

if sys.argv[1] == "on":
    RFID_STATE = 1
    print('start rfid')
elif sys.argv[1] == "off":
    RFID_STATE = 0
    print('stop rfid')
else:
    print('no comprendo')
    exit()

HOST = '127.0.0.1'
PORT = 12345

client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
client.connect((HOST, PORT))

#                       MAGIC                       type    size        type    argc    args[...]
command_rfid = bytes([  0x41, 0x42, 0x13, 0x56,     0,      0, 3,       0x17,   1,      RFID_STATE])

n = client.send(command_rfid)
if (n != len(command_rfid)):
    print ('Erreur envoi.')

time.sleep(1)
client.close()
